//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_LEAVE
    {
        public int ID { get; set; }
        public Nullable<int> ID_TEACHER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string REASON { get; set; }
        public string STATUS { get; set; }
    
        public virtual TEACHER TEACHER { get; set; }
    }
}
