//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_IS_TAKEN
    {
        public int ID { get; set; }
        public Nullable<int> ID_ROOM { get; set; }
        public Nullable<int> ID_TIME_SLOT { get; set; }
    
        public virtual ROOM ROOM { get; set; }
        public virtual TIME_SLOT TIME_SLOT { get; set; }
    }
}
