//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHER()
        {
            this.CLASSROOMs = new HashSet<CLASSROOM>();
            this.SUBJECTs = new HashSet<SUBJECT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_TEACHERTYPE { get; set; }
        public Nullable<int> ID_ACADEMIC_RANK { get; set; }
        public string NAME { get; set; }
    
        public virtual ACADEMIC_RANK ACADEMIC_RANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASSROOM> CLASSROOMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBJECT> SUBJECTs { get; set; }
        public virtual TEACHER_TYPE TEACHER_TYPE { get; set; }
    }
}
