//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_SCHEDULE
    {
        public int ID { get; set; }
        public Nullable<int> ID_TEACHER_CHECK { get; set; }
        public Nullable<int> ID_SUBJECT { get; set; }
        public Nullable<int> ID_ROOM { get; set; }
        public Nullable<int> NUMBER_STUDENT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TIMESTART { get; set; }
        public string TIME { get; set; }
    
        public virtual ROOM ROOM { get; set; }
        public virtual TEACHER TEACHER { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
