//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceramics_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public int STT { get; set; }
        public Nullable<int> MASP { get; set; }
        public string ID_USER { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
