//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceramics_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANHSP
    {
        public int MAANH { get; set; }
        public Nullable<int> MASP { get; set; }
        public string TENANH { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
