//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceramics_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.HINHANHSPs = new HashSet<HINHANHSP>();
        }
    
        public int MASP { get; set; }
        public Nullable<int> MACL { get; set; }
        public Nullable<int> MALSP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> CHIEURONG { get; set; }
        public Nullable<decimal> CHIEUCAO { get; set; }
        public string MOTA { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public Nullable<int> SOLUONGTONKHO { get; set; }
        public Nullable<int> SOLUONGDABAN { get; set; }
        public Nullable<decimal> GIA { get; set; }
    
        public virtual CHATLIEU CHATLIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANHSP> HINHANHSPs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
