//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ceramics_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINCUAHANG
    {
        public int MATT { get; set; }
        public string TENCH { get; set; }
        public string DIACHI { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string FLUGINPAGE { get; set; }
        public string URLMAP { get; set; }
    }
}
